spring.application.name=offerOps

# Database Connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate Configurations
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.hibernate.ddl-auto=update

# Security Constants
jwt.expiry=${JWT_EXPIRY}
jwt.secret=${JWT_SECRET}

# Server Config
server.port=${SERVER_PORT}

resend.api.key=${RESEND_API_KEY}
resend.from.address=${MAIL_FROM_ADDRESS}

# Internal App Secrets
app.internal.secret=${INTERNAL_SECRET}


app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}


#
# Auth0
# === Auth0 Config ===
spring.security.oauth2.client.registration.auth0.client-id=${AUTH0_CLIENT_ID}
spring.security.oauth2.client.registration.auth0.client-secret=${AUTH0_CLIENT_SECRET}
spring.security.oauth2.client.registration.auth0.scope=openid,profile,email
# Providers (these specify the external endpoints)
spring.security.oauth2.client.provider.auth0.issuer-uri=${AUTH0_ISSUER_URI}
spring.security.oauth2.client.provider.auth0.authorization-uri=${AUTH0_ISSUER_URI}authorize?prompt=select_account

# Allow the session cookie to survive the OAuth2 redirect callback
server.servlet.session.cookie.same-site=lax
app.oauth2.redirect-uri=${OAUTH2_SUCCESS_REDIRECT_URI}
# Explicitly link the client registration to the provider
spring.security.oauth2.client.registration.auth0.provider=auth0

# Send client credentials in the POST body for auth 0
spring.security.oauth2.client.registration.auth0.client-authentication-method=client_secret_post