spring.application.name=offerOps

spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USERNAME}

spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.hibernate.ddl-auto=update


jwt.expiry=3600
jwt.secret=9f3d7c2a8b1e5f6a7d8c9e0f1a2b3c4d5e6f7a8b9c0d1e2f

server.port=7474